add validation of the selected date and show error message as well
LykkeCity/WalletCoreiOS pull request #71
Opened 2018-07-02 07:04 UTC by StoykovPrime

2018-07-02 07:39 UTC, vladimirdimovprimeholding approved these changes

2018-07-09 13:21 UTC, StanevPrime requested changes

2018-07-09 13:21 UTC, StanevPrime commented on WalletCore/Classes/ViewModel/TransactionFilterViewModel.swift
> +    func compareDate(startDate: Date?, withDate endDate:Date?) -> Bool {
Please move this logic in Date extension, so can be used across the whole module

2018-07-10 11:29 UTC, vladimirdimovprimeholding approved these changes

2018-07-11 13:41 UTC, vladimirdimovprimeholding approved these changes

2018-07-12 12:13 UTC, StanevPrime approved these changes

2018-07-18 11:14 UTC, whoislyuboanyway approved these changes

2018-07-18 11:55 UTC, merged