Bugfix/lmw 510
LykkeCity/WalletCoreiOS pull request #72
Opened 2018-07-02 10:34 UTC by vladimirdimovprimeholding

2018-07-03 06:34 UTC, StoykovPrime approved these changes

2018-07-04 12:03 UTC, StoykovPrime approved these changes

2018-07-09 12:36 UTC, StanevPrime requested changes

2018-07-09 12:36 UTC, StanevPrime commented on WalletCore/Classes/ViewModel/CashOut/CashOutBankAccountViewModel.swift
> +                $0[0].isNotEmpty &&
Please, iterate over the array instead of pointing each item individually.Functional loop would be the better approach in this case.

2018-07-09 12:36 UTC, StanevPrime commented on WalletCore/Classes/ViewModel/CashOut/CashOutViewModel.swift
> +    private let countryCodes = Variable<[LWCountryModel]>([])
Do you need ViewModel's property countryCodes.Does not look that it's used within the ViewModel itself ?

2018-07-10 11:35 UTC, StoykovPrime approved these changes

2018-07-12 11:38 UTC, StanevPrime approved these changes

2018-07-13 07:49 UTC, merged